[project]
name = "rag-cancer-myth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "bs4>=0.0.2",
    "httpx>=0.28.1",
    "numpy>=2.5.2",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
    "qdrant-client>=1.19.0",
    "rank-bm25>=0.2.2",
    "requests>=2.34.2",
    "sentence-transformers>=6.0.1",
    "streamlit>=1.62.0",
    "tqdm>=4.70.0",
]
